rango/urls.py
from django.conf.urls import patterns, url
from rango import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    #url(r'^register/$', views.register, name = 'register'),
    #url(r'^login/$', views.user_login, name='login'),
    #url(r'^logout/$', views.user_logout, name = 'logout'),
    url(r'^restricted/', views.restricted, name = 'restricted'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
) 

tango_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(selfself,request, user):
        return '/rango/'


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tango_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^rango/', include('rango.urls', namespace = "rango")),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)
if settings.DEBUG:
    urlpatterns += patterns(
            'django.views.static',
            (r'^media/(?P<path>.*)',
            'serve',
            {'document_root': settings.MEDIA_ROOT}),)

rango/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

# Create your models here.

class UserProfile(models.Model):
	# Link userprofile to user model instance
	user = models.OneToOneField(User)
	website = models.URLField(blank = True)
	picture = models.ImageField(upload_to = 'profile_images', blank = True)

	def __unicode__(self):
		return self.user.username

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
    	self.slug = slugify(self.name)
    	super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title
    

rango/forms.py
from django import forms
from django.contrib.auth.models import User
from rango.models import Page, Category, UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
	title = forms.CharField(max_length = 128, help_text = "Please enter the page title.")
	url = forms.URLField(max_length = 200, help_text = "Please enter the page urlno.")
	views = forms.IntegerField(widget = forms.HiddenInput(), initial = 0)

	class Meta:
		model = Page

		exclude = ('category',)

class UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('website', 'picture')

rango/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm
from rango.forms import UserForm, UserProfileForm
from datetime import datetime


def index(request):
    category_list = Category.objects.order_by('-likes')[:8]
    page_list = Page.objects.order_by('-views')[:5]
    context_dict = {'categories' : category_list, 'pages' : page_list,}

    visits = request.session.get('visits')
    if not visits:
        visits = 1
    reset_last_visit_time = False

    last_visit = request.session.get('last_visit')
    if last_visit:
        last_visit_time = datetime.strptime(last_visit[:-7], "%Y-%m-%d %H:%M:%S")

        if (datetime.now() - last_visit_time).days > 0:
            # ...reassign the value of the cookie to +1 of what it was before...
            visits = visits + 1
            # ...and update the last visit cookie, too.
            reset_last_visit_time = True
    else:
        # Cookie last_visit doesn't exist, so create it to the current date/time.
        reset_last_visit_time = True

    if reset_last_visit_time:
        request.session['last_visit'] = str(datetime.now())
        request.session['visits'] = visits
    context_dict['visits'] = visits


    response = render(request,'rango/index.html', context_dict)

    return response

#def register (request):
#	registered = False
#
#	if request.method == 'POST':
#
#		user_form = UserForm(data = request.POST)
#		profile_form = UserProfileForm(data = request.POST)
#
#		if user_form.is_valid() and profile_form.is_valid():
#
#			user = user_form.save()
#
#			user.set_password(user.password)
#			user.save()
#
#			profile = profile_form.save(commit = False)
#			profile.user = user
#
#			if 'picture' in request.FILES:
#				profile.picture = request.FILES['picture']
#
#			profile.save()
#
#			registered = True
#
#		else:
#			print user_form.errors, profile_form.errors
#
#	else:
#		user_form = UserForm()
#		profile_form = UserProfileForm()
#
#	return render(request, 'rango/register.html', {'user_form': user_form, 'profile_form' : profile_form, 'registered' : registered})
#
#def user_login(request):
	
#	if request.method == 'POST':
#		username = request.POST['username']
#		password = request.POST['password']
#
#		user = authenticate(username = username, password = password)
#
#		if user:
#			if user.is_active:
#
#				login(request, user)
#				return HttpResponseRedirect('/rango/')
#
#			else:
#
#				return HttpResponse("Your Rango account is disabled.")
#
#		else:
#
#			print "Invalid login details: {0}, {1}".format(username, password)
#			return HttpResponse("Invalid login details supplied.")
#
#	else:
#
#		return render(request, 'rango/login.html', {})

#@login_required
#def user_logout(request):
#	logout(request)
#
#	return HttpResponseRedirect('/rango/')

def category(request, category_name_slug):
	#create a  context dictionary to pass in to template engine
	context_dict = {}
	try:
		#get category name from db if there, and add to context dict
		category = Category.objects.get(slug = category_name_slug)
		context_dict['category_name'] = category.name

		#get pages of the the particular category if any add to context dict
		pages = Page.objects.filter(category = category)
		context_dict['pages'] = pages

		#we'll need category object in template to verify if category exist
		context_dict['category'] = category

		context_dict['category_name_slug'] = category_name_slug

	except Category.DoesNotExist:
		#doesn't need to do anything
		pass   									

	return render(request, 'rango/category.html', context_dict)



@login_required
def restricted(request):
	return (render (request, 'rango/restricted.html', {}))

def about(request):
    
    return render(request,'rango/about.html',{})

@login_required
def add_category(request):
	if request.method == "POST":
		form = CategoryForm(request.POST)

		if form.is_valid():
			cat = form.save(commit=True)
			return index(request)

		else:
			print form.errors

	else:
		form = CategoryForm()

	return render(request, 'rango/add_category.html', {'form' : form})


@login_required
def add_page(request, category_name_slug):
	
	try:
		cat = Category.objects.get(slug = category_name_slug)

	except Category.DoesNotExist:
		cat = None 

	if request.method == 'POST':
		form = PageForm(request.POST)
		if form.is_valid():
			if cat:
				page = form.save(commit = False)
				page.category = cat
				page.views = 0
				page.save()
				return category(request, category_name_slug)
		else:
			print form.errors

	else:
		form = PageForm()

	context_dict = {'form': form, 'category': cat, 'category_name_slug': category_name_slug}

	return render(request, 'rango/add_page.html', context_dict)

templates/rango/about.html
{% extends 'rango/base.html' %}
{% block title %} About Us {% endblock %}

{% block body_block %}

        <h1>About Us</h1>
        <a href = "{% url 'rango:index' %}">Home</a><br/><br/>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% block title %} add_category {% endblock %}

{% block body_block %}

	<body>
		<h1>Add a Category</h1>

		<form id ="category_form" method="post" action="{% url 'rango:add_category' %}">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}

			{% for field in form.visible_fields %}
				{{ field.errors }}
				{{ field.help_text }}
				{{ field }}<br/><br/>
			{% endfor %}

			<input type="submit" name="submit" value="Create Category"/>
		</form>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}

{% block title %}Add Page{% endblock %}


{% block body_block %}
{% if category %}

                <form role="form"  id="page_form" method="post" action="{% url 'rango:add_page' category_name_slug %}">
            <h2 class="form-signin-heading">Add a Page to <a href="/rango/category/{{category.slug}}/"> {{ category.name }}</a></h2>
                    {% csrf_token %}
                    {% for hidden in form.hidden_fields %}
                        {{ hidden }}
                    {% endfor %}

                    {% for field in form.visible_fields %}
                        {{ field.errors }}
                        {{ field.help_text }}<br/>
                        {{ field }}<br/>
                    {% endfor %}

                <br/>
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
                </form>
            {%  else %}
            <p>This is category does not exist.</p>
        {%  endif %}


        {% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load rango_extras %}
{% get_category_list %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://getbootstrap.com/favicon.ico">

    <title>Rango - {% block title %}How to Tango with Django!{% endblock %}</title>

    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/rango/">Rango</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'rango:index' %}">Home</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                        <li><a href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                    {% else %}
                        <li><a href="{% url 'registration_register' %}">Register Here</a></li>
                        <li><a href="{% url 'auth_login' %}">Login</a></li>
                    {% endif %}
                                <li><a href="{% url 'rango:about' %}">About</a></li>

              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
                {% block side_block %}{% get_category_list %}{% endblock %}

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
           <div>
                {% block body_block %}{% endblock %}
                </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
		
	<h1>{{ category_name }}</h1>
	{% if category %}
		{% if pages %}
		<ul>
			{% for page in pages %}
			<li><a href="{{ page.url }}">{{ page.title }}</a></li>
			{% endfor %}
		</ul>

		{% else %}
			<strong> No pages currently in {{ category_name }} . </strong>
		{% endif %}
		{% if user.is_authenticated %}

			<a href="{% url 'rango:add_page' category_name_slug %}"><h1>Add Page</h1></a>		

		{% endif %}

	{% else %}
		The specified category {{category_name}} does not exists!
	{% endif %}
{% endblock %}

templates/rango/cats.html
{% for c in cats %}
    {% if c == act_cat %} <li  class="active" > {% else  %} <li>{% endif %}
            <a href="{% url 'rango:category'  c.slug %}">{{ c.name }}</a></li>
{% endfor %}

templates/rango/index.html
{% extends 'rango/base.html' %}

{% load staticfiles %}

{% block title %}Index{% endblock %}

        {% block body_block %}
{% if user.is_authenticated %}
    <div class="page-header">

                <h1>Rango says... hello {{ user.username }}!</h1>
            {% else %}
                <h1>Rango says... hello world!</h1>
            {% endif %}
    </div>

         <div class="row placeholders">
            <div class="col-xs-12 col-sm-6 placeholder">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Categories</h3>
                    </div>
                </div>

              {% if categories %}
                    <ul class="list-group">
                        {% for category in categories %}
                         <li class="list-group-item"><a href="{% url 'rango:category'  category.slug %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no categories present.</strong>
                {% endif %}

            </div>
            <div class="col-xs-12 col-sm-6 placeholder">
              
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">Pages</h3>
                    </div>
                </div>

                {% if pages %}
                    <ul class="list-group">
                        {% for page in pages %}
                         <li class="list-group-item"><a href="{{page.url}}">{{ page.title }}</a></li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <strong>There are no categories present.</strong>
                {% endif %}
            </div>

          </div>


       <p> visits: {{ visits }}</p>
        {% endblock %}

templates/rango/login.html
{% block body_block %}

<link href="http://getbootstrap.com/examples/signin/signin.css" rel="stylesheet">

<form class="form-signin" role="form" method="post" action=".">
{% csrf_token %}

<h2 class="form-signin-heading">Please sign in</h2>
<input class="form-control" placeholder="Username" id="id_username" maxlength="254" name="username" type="text" required autofocus=""/>
<input type="password" class="form-control" placeholder="Password" id="id_password" name="password" type="password" required />

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Submit" />Sign in</button>
        </form>

{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% block title %} Register {% endblock %}

{% block body_block %}

		<h1> Register with Rango</h1>

		{% if registered  %}

		Rango says: <strong>thank you for registering!</strong>
		<a href ="{% url 'rango:index' %}">Return to the homepage.</a><br/>

		{% else %}

		Rango says: <strong> register here!</strong> 
		click <a href="{% url 'rango:index' %}">here</a> to go to homepage <br/>

		<form id = 'user_form' method = 'post' acition ='{% url 'rango:register' %}' enctype = 'multipart/form-data'>

			{% csrf_token %}

			{{ user_form.as_p }}
			{{ profile_form.as_p }}

			<input type = 'submit' name = 'submit' value = 'Register' />

		</form>
		{% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% block title %} restricted Us {% endblock %}

{% block body_block %}
	<h1> You can see this Page 'cause you're logged in </h1>
{% endblock %}